In [1]:
import numpy as np

In [16]:
C = np.array([[2.0, 3.0], [1.0, -4.0]])
D = np.array([[1.0, 2.0], [5.0, -5.0]])

print(C)
print(C.shape)
print(D)
print(D.shape)

[[ 2.  3.]
 [ 1. -4.]]
(2, 2)
[[ 1.  2.]
 [ 5. -5.]]
(2, 2)


In [17]:
D.T

array([[ 1.,  5.],
       [ 2., -5.]])

In [18]:
print(C + D)

[[ 3.  5.]
 [ 6. -9.]]


In [19]:
print(C @ D)

[[ 17. -11.]
 [-19.  22.]]


In [21]:
print(np.dot(C,D))

[[ 17. -11.]
 [-19.  22.]]


In [25]:
E = np.zeros((100, 100))

In [29]:
F = 5.0 * np.ones((100, 100))
print(F)

[[ 5.  5.  5. ...,  5.  5.  5.]
 [ 5.  5.  5. ...,  5.  5.  5.]
 [ 5.  5.  5. ...,  5.  5.  5.]
 ..., 
 [ 5.  5.  5. ...,  5.  5.  5.]
 [ 5.  5.  5. ...,  5.  5.  5.]
 [ 5.  5.  5. ...,  5.  5.  5.]]


In [31]:
H = np.nan * np.ones((100, 100))
print(H)

[[ nan  nan  nan ...,  nan  nan  nan]
 [ nan  nan  nan ...,  nan  nan  nan]
 [ nan  nan  nan ...,  nan  nan  nan]
 ..., 
 [ nan  nan  nan ...,  nan  nan  nan]
 [ nan  nan  nan ...,  nan  nan  nan]
 [ nan  nan  nan ...,  nan  nan  nan]]


In [40]:
T = np.diagflat(2.0*np.ones((3,1)))
Tp1 = np.diagflat(-1.0*np.ones((2,1)), 1)
Tm1 = np.diagflat(-1.0*np.ones((2,1)),-1)

print(T)
print(Tp1)
print(Tm1)

[[ 2.  0.  0.]
 [ 0.  2.  0.]
 [ 0.  0.  2.]]
[[ 0. -1.  0.]
 [ 0.  0. -1.]
 [ 0.  0.  0.]]
[[ 0.  0.  0.]
 [-1.  0.  0.]
 [ 0. -1.  0.]]


In [41]:
print(T + Tp1 + Tm1)

[[ 2. -1.  0.]
 [-1.  2. -1.]
 [ 0. -1.  2.]]
